open("C:/Users/rusch051/Desktop/20230385-20230399_PG/20230235_0_4_PG/Clean/20230235a_T0_10xstitch_PG_CLN.jpg");
selectImage("20230235a_T0_10xstitch_PG_CLN.jpg");
run("Duplicate...", " ");
selectImage("20230235a_T0_10xstitch_PG_CLN.jpg");
selectImage("20230235a_T0_10xstitch_PG_CLN-1.jpg");
run("Color Threshold...");
// Color Thresholder 2.14.0/1.54f
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=0;
max[0]=255;
filter[0]="pass";
min[1]=0;
max[1]=255;
filter[1]="pass";
min[2]=0;
max[2]=219;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------



